/* nngen_driver.c -- see nngen_driver.h. Generated by NNgen (nngen/c_header.py). */
#include "nngen_driver.h"

void nngen_soft_reset(const nngen_dev_t *d)
{
  nngen_write(d, NNGEN_REG_RESET, 1);
  while (nngen_read(d, NNGEN_REG_BUSY) != 0) { }
}

int nngen_init(nngen_dev_t *d, uintptr_t reg_base, uint32_t ddr_global_offset,
               const nngen_model_t *model)
{
  uint32_t i;
  d->base = reg_base;
  d->global_offset = ddr_global_offset;
  nngen_soft_reset(d);
  nngen_write(d, NNGEN_REG_GLOBAL_OFFSET, ddr_global_offset);
  if (model) {
    for (i = 0; i < model->num_regions; i++)
      nngen_write(d, model->regions[i].reg, model->regions[i].default_offset);
    if (nngen_read(d, NNGEN_REG_ADDRESS_AMOUNT) != model->address_space_amount)
      return -1; /* header and bitstream do not match */
  }
  nngen_irq_ack(d, 0xffffffffu);
  return 0;
}

int nngen_set_region_addr(const nngen_dev_t *d, uint32_t addr_reg, uint32_t ddr_addr)
{
  if (ddr_addr < d->global_offset) return -1;
  nngen_write(d, addr_reg, ddr_addr - d->global_offset);
  return 0;
}

uint32_t nngen_get_region_addr(const nngen_dev_t *d, uint32_t addr_reg)
{
  return d->global_offset + nngen_read(d, addr_reg);
}

uint32_t nngen_default_region_addr(const nngen_dev_t *d, const nngen_region_t *r)
{
  return d->global_offset + r->default_offset;
}

void nngen_start(const nngen_dev_t *d)
{
  nngen_write(d, NNGEN_REG_START, 1);
  /* START reads back non-zero until the main FSM has accepted the request */
  while (nngen_read(d, NNGEN_REG_START) != 0) { }
}

int nngen_wait(const nngen_dev_t *d, uint32_t timeout_loops)
{
  while (nngen_read(d, NNGEN_REG_BUSY) != 0) {
    if (timeout_loops) {
      if (--timeout_loops == 0) return -1;
    }
  }
  return 0;
}
