/*
 * nngen_driver.h -- minimal model-agnostic bare-metal driver for NNgen accelerators.
 * Generated by NNgen (nngen/c_header.py). Include this BEFORE <model>_nngen.h to get
 * the region table (<model>_model).
 *
 * The accelerator is an AXI-Lite slave (32-bit registers) plus an AXI4 master that
 * reads/writes DDR. DMA address of every region = GLOBAL_OFFSET + region register.
 * The driver never touches DDR itself: loading the parameter image and the input
 * tensor, and reading the output tensor, is done by the caller (CPU DDR window,
 * DMA, or a mailbox). With a data cache, flush/invalidate around nngen_start().
 */
#ifndef NNGEN_DRIVER_H
#define NNGEN_DRIVER_H

#include <stdint.h>

#define NNGEN_REG_START          0x010u
#define NNGEN_REG_BUSY           0x014u
#define NNGEN_REG_RESET          0x018u
#define NNGEN_REG_ISR            0x024u
#define NNGEN_REG_IER            0x028u
#define NNGEN_REG_IAR            0x02cu
#define NNGEN_REG_COUNT          0x030u
#define NNGEN_REG_COUNT_STATE    0x034u
#define NNGEN_REG_COUNT_DIV      0x038u
#define NNGEN_REG_ADDRESS_AMOUNT 0x07cu
#define NNGEN_REG_GLOBAL_OFFSET  0x080u
#define NNGEN_ISR_BUSY           0x1u

typedef struct {
  uint32_t reg;            /* byte offset of the address register */
  uint32_t default_offset; /* default region offset (relative to GLOBAL_OFFSET) */
  uint32_t size;           /* region size in bytes */
  const char *name;        /* "temporal", "params", "out_<name>", "in_<name>" */
} nngen_region_t;

typedef struct {
  const char *name;
  const nngen_region_t *regions;
  uint32_t num_regions;
  uint32_t param_image_size;
  uint32_t address_space_amount;
} nngen_model_t;

typedef struct {
  uintptr_t base;          /* CPU address of the AXI-Lite register window */
  uint32_t global_offset;  /* DDR base of the model's default memory map */
} nngen_dev_t;

static inline void nngen_write(const nngen_dev_t *d, uint32_t off, uint32_t v)
{ *(volatile uint32_t *)(d->base + off) = v; }
static inline uint32_t nngen_read(const nngen_dev_t *d, uint32_t off)
{ return *(volatile uint32_t *)(d->base + off); }

/* Init: soft reset, program GLOBAL_OFFSET and all address registers with defaults. */
int  nngen_init(nngen_dev_t *d, uintptr_t reg_base, uint32_t ddr_global_offset,
                const nngen_model_t *model);
/* Region address as a DDR address (absolute); must be >= global_offset. */
int  nngen_set_region_addr(const nngen_dev_t *d, uint32_t addr_reg, uint32_t ddr_addr);
uint32_t nngen_get_region_addr(const nngen_dev_t *d, uint32_t addr_reg);
/* Default absolute DDR address of a region of the model. */
uint32_t nngen_default_region_addr(const nngen_dev_t *d, const nngen_region_t *r);
/* Start one inference; waits until the start request has been accepted. */
void nngen_start(const nngen_dev_t *d);
static inline int nngen_busy(const nngen_dev_t *d) { return nngen_read(d, NNGEN_REG_BUSY) != 0; }
/* Poll BUSY until idle. Returns 0, or -1 on timeout (timeout=0: wait forever). */
int  nngen_wait(const nngen_dev_t *d, uint32_t timeout_loops);
/* Interrupt helpers (irq output is level-high while ISR & IER != 0). */
static inline void nngen_irq_enable(const nngen_dev_t *d, int en)
{ nngen_write(d, NNGEN_REG_IER, en ? NNGEN_ISR_BUSY : 0); }
static inline uint32_t nngen_irq_status(const nngen_dev_t *d)
{ return nngen_read(d, NNGEN_REG_ISR); }
static inline void nngen_irq_ack(const nngen_dev_t *d, uint32_t bits)
{ nngen_write(d, NNGEN_REG_IAR, bits); }
/* Soft reset of the internal logic (waits until AXI master is idle). */
void nngen_soft_reset(const nngen_dev_t *d);
/* Cycle counter of main-FSM state `state` (see nngen "measurable_main_fsm"). */
static inline void nngen_count_setup(const nngen_dev_t *d, uint32_t state, uint32_t div)
{ nngen_write(d, NNGEN_REG_COUNT_STATE, state); nngen_write(d, NNGEN_REG_COUNT_DIV, div); }
static inline uint32_t nngen_count(const nngen_dev_t *d) { return nngen_read(d, NNGEN_REG_COUNT); }

#endif /* NNGEN_DRIVER_H */
