/*
 * style_net_nngen.h -- generated by NNgen 1.3.4 (nngen/c_header.py), 2026-10-04
 * DO NOT EDIT: regenerate together with the Verilog of the same model.
 *
 * AXI master : data 16 bit, addr 32 bit, no ID, max burst 256 beats, INCR
 * AXI-Lite   : data 32 bit (32-bit word registers, byte offsets below)
 * IRQ        : level-high "irq", ISR bit0 = busy falling edge
 * DMA address = REG_GLOBAL_OFFSET + region address register.
 */
#ifndef NNGEN_STYLE_NET_H
#define NNGEN_STYLE_NET_H

#include <stdint.h>

/* ---- control registers (byte offsets from the AXI-Lite base) ---- */
#define STYLE_NET_REG_HEADER0          0x000u
#define STYLE_NET_REG_HEADER1          0x004u
#define STYLE_NET_REG_HEADER2          0x008u
#define STYLE_NET_REG_HEADER3          0x00cu
#define STYLE_NET_REG_START            0x010u
#define STYLE_NET_REG_BUSY             0x014u
#define STYLE_NET_REG_RESET            0x018u
#define STYLE_NET_REG_EXTERN_SEND      0x01cu
#define STYLE_NET_REG_EXTERN_RECV      0x020u
#define STYLE_NET_REG_ISR              0x024u
#define STYLE_NET_REG_IER              0x028u
#define STYLE_NET_REG_IAR              0x02cu
#define STYLE_NET_REG_COUNT            0x030u
#define STYLE_NET_REG_COUNT_STATE      0x034u
#define STYLE_NET_REG_COUNT_DIV        0x038u
#define STYLE_NET_REG_ADDRESS_AMOUNT   0x07cu
#define STYLE_NET_REG_GLOBAL_OFFSET    0x080u
#define STYLE_NET_HAS_IRQ               1
#define STYLE_NET_ISR_BUSY_BIT          0

/* ---- build configuration ---- */
#define STYLE_NET_MAXI_DATAWIDTH        16
#define STYLE_NET_CHUNK_BYTES           64
#define STYLE_NET_DEFAULT_GLOBAL_OFFSET 0x00000000u
#define STYLE_NET_ADDRESS_SPACE_AMOUNT  1789184u  /* bytes, from default memory map */
#define STYLE_NET_NUM_ADDR_REGS         4

/* ---- address registers: one per region (offsets relative to GLOBAL_OFFSET) ---- */
/* temporal: temporal */
#define STYLE_NET_TEMPORAL_REG            0x084u
#define STYLE_NET_TEMPORAL_DEFAULT_OFFSET 0x0002ad00u
#define STYLE_NET_TEMPORAL_SIZE           1613824u

/* output: /head/Conv */
#define STYLE_NET_OUT_HEAD_CONV_REG            0x088u
#define STYLE_NET_OUT_HEAD_CONV_DEFAULT_OFFSET 0x00000000u
#define STYLE_NET_OUT_HEAD_CONV_SIZE           65536u
#define STYLE_NET_OUT_HEAD_CONV_N              1
#define STYLE_NET_OUT_HEAD_CONV_H              128
#define STYLE_NET_OUT_HEAD_CONV_W              128
#define STYLE_NET_OUT_HEAD_CONV_C              3
#define STYLE_NET_OUT_HEAD_CONV_ALIGNED_C      4  /* innermost dim padded to word alignment */
#define STYLE_NET_OUT_HEAD_CONV_DTYPE_BITS     8  /* int8 */
#define STYLE_NET_OUT_HEAD_CONV_SCALE_FACTOR   59.7778031f  /* real = int / SCALE_FACTOR */
/* layout: NHWC, element (n,h,w,c) at byte offset ((n*H+h)*W+w)*ALIGNED_C+c (int8) */

/* input: act */
#define STYLE_NET_IN_ACT_REG            0x08cu
#define STYLE_NET_IN_ACT_DEFAULT_OFFSET 0x00010000u
#define STYLE_NET_IN_ACT_SIZE           65536u
#define STYLE_NET_IN_ACT_N              1
#define STYLE_NET_IN_ACT_H              128
#define STYLE_NET_IN_ACT_W              128
#define STYLE_NET_IN_ACT_C              4
#define STYLE_NET_IN_ACT_ALIGNED_C      4  /* innermost dim padded to word alignment */
#define STYLE_NET_IN_ACT_DTYPE_BITS     8  /* int8 */
#define STYLE_NET_IN_ACT_SCALE_FACTOR   128.0f  /* real = int / SCALE_FACTOR */
/* layout: NHWC, element (n,h,w,c) at byte offset ((n*H+h)*W+w)*ALIGNED_C+c (int8) */

/* params: params */
#define STYLE_NET_PARAMS_REG            0x090u
#define STYLE_NET_PARAMS_DEFAULT_OFFSET 0x00020000u
#define STYLE_NET_PARAMS_SIZE           44288u

/* ---- parameter image (ng.export_ndarray, chunk 64 B): 44288 bytes, 51 tensors ---- */
#define STYLE_NET_PARAM_IMAGE_SIZE      44288u
/*   +0x000000    576 B int8   (16, 3, 3, 4)            onnx::Conv_188 */
/*   +0x000240     64 B int32  (16,)                    onnx::Conv_189 */
/*   +0x000280     64 B int32  (1,)                     onnx_/stem/stem.0/Conv_conv.scale */
/*   +0x0002c0   1024 B int8   (64, 1, 1, 16)           onnx::Conv_191 */
/*   +0x0006c0    256 B int32  (64,)                    onnx::Conv_192 */
/*   +0x0007c0     64 B int32  (1,)                     onnx_/enc2/enc2.0/conv/conv.0/conv.0.0/Conv_conv.scale */
/*   +0x000800    576 B int8   (3, 3, 64)               onnx_/enc2/enc2.0/conv/conv.1/conv.1.0/Conv_dwconv.filter */
/*   +0x000a40    256 B int32  (64,)                    onnx_/enc2/enc2.0/conv/conv.1/conv.1.0/Conv_dwconv.bias */
/*   +0x000b40    256 B int32  (64,)                    onnx_/enc2/enc2.0/conv/conv.1/conv.1.0/Conv_dwconv.scale */
/*   +0x000c40   1536 B int8   (24, 1, 1, 64)           onnx::Conv_197 */
/*   +0x001240    128 B int32  (24,)                    onnx::Conv_198 */
/*   +0x0012c0     64 B int32  (1,)                     onnx_/enc2/enc2.0/conv/conv.2/conv.2.0/Conv_conv.scale */
/*   +0x001300   2304 B int8   (96, 1, 1, 24)           onnx::Conv_200 */
/*   +0x001c00    384 B int32  (96,)                    onnx::Conv_201 */
/*   +0x001d80     64 B int32  (1,)                     onnx_/enc2/enc2.1/conv/conv.0/conv.0.0/Conv_conv.scale */
/*   +0x001dc0    896 B int8   (3, 3, 96)               onnx_/enc2/enc2.1/conv/conv.1/conv.1.0/Conv_dwconv.filter */
/*   +0x002140    384 B int32  (96,)                    onnx_/enc2/enc2.1/conv/conv.1/conv.1.0/Conv_dwconv.bias */
/*   +0x0022c0    384 B int32  (96,)                    onnx_/enc2/enc2.1/conv/conv.1/conv.1.0/Conv_dwconv.scale */
/*   +0x002440   2304 B int8   (24, 1, 1, 96)           onnx::Conv_206 */
/*   +0x002d40    128 B int32  (24,)                    onnx::Conv_207 */
/*   +0x002dc0     64 B int32  (1,)                     onnx_/enc2/enc2.1/conv/conv.2/conv.2.0/Conv_conv.scale */
/*   +0x002e00   2304 B int8   (96, 1, 1, 24)           onnx::Conv_209 */
/*   +0x003700    384 B int32  (96,)                    onnx::Conv_210 */
/*   +0x003880     64 B int32  (1,)                     onnx_/enc3/enc3.0/conv/conv.0/conv.0.0/Conv_conv.scale */
/*   +0x0038c0    896 B int8   (3, 3, 96)               onnx_/enc3/enc3.0/conv/conv.1/conv.1.0/Conv_dwconv.filter */
/*   +0x003c40    384 B int32  (96,)                    onnx_/enc3/enc3.0/conv/conv.1/conv.1.0/Conv_dwconv.bias */
/*   +0x003dc0    384 B int32  (96,)                    onnx_/enc3/enc3.0/conv/conv.1/conv.1.0/Conv_dwconv.scale */
/*   +0x003f40   3072 B int8   (32, 1, 1, 96)           onnx::Conv_215 */
/*   +0x004b40    128 B int32  (32,)                    onnx::Conv_216 */
/*   +0x004bc0     64 B int32  (1,)                     onnx_/enc3/enc3.0/conv/conv.2/conv.2.0/Conv_conv.scale */
/*   +0x004c00   4096 B int8   (128, 1, 1, 32)          onnx::Conv_218 */
/*   +0x005c00    512 B int32  (128,)                   onnx::Conv_219 */
/*   +0x005e00     64 B int32  (1,)                     onnx_/enc3/enc3.1/conv/conv.0/conv.0.0/Conv_conv.scale */
/*   +0x005e40   1152 B int8   (3, 3, 128)              onnx_/enc3/enc3.1/conv/conv.1/conv.1.0/Conv_dwconv.filter */
/*   +0x0062c0    512 B int32  (128,)                   onnx_/enc3/enc3.1/conv/conv.1/conv.1.0/Conv_dwconv.bias */
/*   +0x0064c0    512 B int32  (128,)                   onnx_/enc3/enc3.1/conv/conv.1/conv.1.0/Conv_dwconv.scale */
/*   +0x0066c0   4096 B int8   (32, 1, 1, 128)          onnx::Conv_224 */
/*   +0x0076c0    128 B int32  (32,)                    onnx::Conv_225 */
/*   +0x007740     64 B int32  (1,)                     onnx_/enc3/enc3.1/conv/conv.2/conv.2.0/Conv_conv.scale */
/*   +0x007780   6912 B int8   (24, 3, 3, 32)           onnx::Conv_227 */
/*   +0x009280    128 B int32  (24,)                    onnx::Conv_228 */
/*   +0x009300     64 B int32  (1,)                     onnx_/dec3/dec3.0/Conv_conv.scale */
/*   +0x009340   3456 B int8   (16, 3, 3, 24)           onnx::Conv_230 */
/*   +0x00a0c0     64 B int32  (16,)                    onnx::Conv_231 */
/*   +0x00a100     64 B int32  (1,)                     onnx_/dec2/dec2.0/Conv_conv.scale */
/*   +0x00a140   2304 B int8   (16, 3, 3, 16)           onnx::Conv_233 */
/*   +0x00aa40     64 B int32  (16,)                    onnx::Conv_234 */
/*   +0x00aa80     64 B int32  (1,)                     onnx_/dec1/dec1.0/Conv_conv.scale */
/*   +0x00aac0    448 B int8   (3, 3, 3, 16)            head.weight */
/*   +0x00ac80     64 B int32  (3,)                     head.bias */
/*   +0x00acc0     64 B int32  (1,)                     onnx_/head/Conv_conv.scale */

/* ---- region table for nngen_driver.c ---- */
#ifdef NNGEN_DRIVER_H
static const nngen_region_t style_net_regions[] = {
  { 0x084u, 0x0002ad00u, 1613824u, "temporal" },
  { 0x088u, 0x00000000u, 65536u, "out_head_conv" },
  { 0x08cu, 0x00010000u, 65536u, "in_act" },
  { 0x090u, 0x00020000u, 44288u, "params" },
};
static const nngen_model_t style_net_model = {
  "style_net", style_net_regions, 4, 44288u, 1789184u
};
#endif

#endif /* NNGEN_STYLE_NET_H */
